### ISSUE TITLE
Add passive touch events option

### ISSUE THREAD

**Issue by unformatt** [ag-grid/ag-grid#1624]
- [x] feature request

**Current behavior**

ag-grid's non-passive touch events cause Chrome to print dozens of warnings and blocks scrolling/rendering. I tried `suppressTouch="true"` and still got the warnings.

`[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.`

![image](https://cloud.githubusercontent.com/assets/157132/25722252/78bed390-30e1-11e7-9c4e-369f2625e736.png)

![image](https://cloud.githubusercontent.com/assets/157132/25722205/4dbfdf18-30e1-11e7-84d8-4164e9d0fd92.png)

**Expected behavior**

No warnings in console

**Minimal reproduction of the problem with instructions**
1. Turn on Verbose console in Chrome
![image](https://cloud.githubusercontent.com/assets/157132/25722517/869b7792-30e2-11e7-8a8b-788f48ad338d.png)

2. Render an ag-grid. Interact or scroll with ag-grid.

**What is the motivation / use case for changing the behavior?**

- Improve performance
- Reduce large amount of warnings in Chrome

**Please tell us about your environment:**
MacOS Sierra, Webpack 1.12.9, React 15.3.2, Babel 6

* **ag-Grid version:** 8.0.0 (also tested with 8.2.0)

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

* **Language:** 
ES6

**Comment by seanlandsman** [comment]
Hi

We already have an issue for this (AG-441) - we'll update this thread with updates as soon as we have any

thanks

**Comment by don-bluelinegrid** [comment]
Also experiencing this - hundreds of warnings printing in console.

As a side note/question - For a desktop component, why are touchevents used?  Is this something that should be disabled by default?

**Comment by seanlandsman** [comment]
@don-bluelinegrid the grid can be used on mobile devices too, typically tablets which is wheret he touch events come into play

**Comment by don-bluelinegrid** [comment]
@seanlandsman 

Right, understood.

The question really was:

a. Should this be disabled by default.
b. Is there a way to completely disable the touchevents, in the case where they are not needed/used.

Thanks,
Don

**Comment by seanlandsman** [comment]
Yeah, I understand - was just pointing out that thats why they're there.

The points you raise will be dealt with by the jira we've created - I cant tell how this change would be implemented, but I've made a note of your comments

thanks

**Comment by PranKe01** [comment]
I am using AG-Grid v14.0.0 and I am still getting warnings:

[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event.
Line 1750: eElement.addEventListener(event, listener, (Utils.passiveEvents.indexOf(event) > -1 ? { passive: true } : null));

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.
Line 17619: params.eElement.addEventListener('touchstart', touchListener, { passive: false });

**Comment by makinggoodsoftware** [comment]
This is tracked by AG-441 Check our pipeline https://www.ag-grid.com/ag-grid-pipeline/ for more information, thanks

**Comment by dangrussell** [comment]
This issue is still present and has now been in the backlog for 4 years. Any updates on AG-441?

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

This issue was reported a long time ago and fixed in AG Grid v21 (2019). This is why this issue was closed originally but the pipeline item remained open in error. I've now closed this AG-441 to avoid confusion.

However, this issue was recently reintroduced in AG Grid v26.0 (in 2021). This is why we have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6286 [Regression] When initially rendering the grid in Chrome, multiple console warnings are output about non-passive event listeners being added**

**This bug will be fixed in our next release scheduled for early February  - v27.0.**

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by 0815pascal** [comment]
@kiril-matev That's great news, thank you very much!!

**Comment by air2** [comment]
Is still see this issue in 28.1.1:

[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
customScheduleGlobal @ zone.js:1752
scheduleTask @ zone.js:393
onScheduleTask @ zone.js:283
scheduleTask @ zone.js:386
scheduleTask @ zone.js:221
scheduleEventTask @ zone.js:247
(anonymous) @ zone.js:1907
addEventListener @ ag-grid-community-angular.js:364
addSafePassiveEventListener @ event.js:124
BeanStub.addManagedListener @ beanStub.js:83
GridBodyCtrl.addBodyViewportListener @ gridBodyCtrl.js:223
GridBodyCtrl.setComp @ gridBodyCtrl.js:71
GridBodyComp.init @ gridBodyComp.js:81
(anonymous) @ context.js:182
Context.callLifeCycleMethodsOnBean @ context.js:182
(anonymous) @ context.js:165
Context.callLifeCycleMethods @ context.js:165
Context.wireBeans @ context.js:44
Context.createBean @ context.js:32
BeanStub.createBean @ beanStub.js:111
Component.createComponentFromElement @ component.js:135
(anonymous) @ component.js:104
Component.createChildComponentsFromTags @ component.js:100
(anonymous) @ component.js:123
Component.createChildComponentsFromTags @ component.js:100
Component.setTemplateFromElement @ component.js:179
Component.setTemplate @ component.js:171
GridComp.postConstruct @ gridComp.js:60
(anonymous) @ context.js:182
Context.callLifeCycleMethodsOnBean @ context.js:182
(anonymous) @ context.js:165
Context.callLifeCycleMethods @ context.js:165
Context.wireBeans @ context.js:44
Context.createBean @ context.js:32
(anonymous) @ grid.js:130
GridCoreCreator.create @ grid.js:167
Grid @ grid.js:128
ngAfterViewInit @ ag-grid-community-angular.js:1318
callHook @ core.js:2538
callHooks @ core.js:2507
executeInitAndCheckHooks @ core.js:2458
refreshView @ core.js:9555
refreshComponent @ core.js:10655
refreshChildComponents @ core.js:9280
refreshView @ core.js:9534
refreshEmbeddedViews @ core.js:10609
refreshView @ core.js:9508
refreshComponent @ core.js:10655
refreshChildComponents @ core.js:9280
refreshView @ core.js:9534
refreshEmbeddedViews @ core.js:10609
refreshView @ core.js:9508
refreshComponent @ core.js:10655
refreshChildComponents @ core.js:9280
refreshView @ core.js:9534
renderComponentOrTemplate @ core.js:9598
tickRootContext @ core.js:10829
detectChangesInRootView @ core.js:10854
detectChanges @ core.js:22874
tick @ core.js:29698
(anonymous) @ core.js:29558
invoke @ zone.js:372
onInvoke @ core.js:28692
invoke @ zone.js:371
run @ zone.js:134
run @ core.js:28546
next @ core.js:29557
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:25955
checkStable @ core.js:28614
onHasTask @ core.js:28709
hasTask @ zone.js:426
_updateTaskCount @ zone.js:447
_updateTaskCount @ zone.js:274
runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:582
invokeTask @ zone.js:491
invokeTask @ zone.js:1600
globalZoneAwareCallback @ zone.js:1637
Show 53 more frames

**Comment by StephenCooper** [comment]
@air2 Could you please provide a reproduction with 28.1. I can see that the reported issue in this ticket and the example we have is fixed in v27 and I cannot reproduce in v28.1

v26.2 - Has the error - https://plnkr.co/edit/Onlv0hJdqfTKzIG2

v27.0 - Has no error - https://plnkr.co/edit/iTGfLiyIEW1TqwZU

v28.1 - Has no error - https://plnkr.co/edit/S3UKA6xSqbcyn2jz

**Comment by air2** [comment]
Yeah this will take some time though, cuz I need to isolate it in a small project, it is currently appearing in a big complicated piece of code. But will do.

**Comment by air2** [comment]
I think this reproduces the issue (in chrome)
https://stackblitz.com/edit/ag-grid-angular-hello-world-c9kly2?file=src/app/app.component.ts

**Comment by air2** [comment]
@StephenCooper any news on this? Is the reproduction okay?

**Comment by StephenCooper** [comment]
Sorry for the delay in getting back to you. I cannot see any error with that reproduction. Also the link above which used to produce the error no longer produces the error.

I am using Chrome Version 107.0.5304.110 and wonder if this is produced by different Chrome versions.

https://user-images.githubusercontent.com/20125490/204770831-8592fc4e-3d8d-420e-b553-3eae35eb57fc.mov

**Comment by air2** [comment]
Let me check, i'll get back to you

**Comment by vahemikayelyan** [comment]
> Sorry for the delay in getting back to you. I cannot see any error with that reproduction. Also the link above which used to produce the error no longer produces the error.
> 
> I am using Chrome Version 107.0.5304.110 and wonder if this is produced by different Chrome versions.
> 
>  Screen.Recording.2022-11-30.at.10.20.53.mov

Hello everyone,

I've been researching this issue a few days and still couldn't figure this out, it still persists even after upgrading to the latest version 30.0.0, and I see the same error when I open the link provided above.

![image](https://github.com/ag-grid/ag-grid/assets/4387264/1c552025-c61d-4c12-958d-62cc8afe3cb5)


Thank you,
Vahe

**Comment by kiril-matev** [comment]
Hello @vahemikayelyan,

Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a regression from v29.3.5.

This issue was fixed in v27.0, and is once again reproducible with AG Grid v30.0 (however only when using Angular).
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-8778 When using Angular, console warning is shown "Added non-passive event listener to a scroll-blocking 'wheel' event."**
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/
 
**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**
 
Thanks again for bringing this up with us - we appreciate your time!

**Comment by vahemikayelyan** [comment]
> Hello @vahemikayelyan,
> 
> Thank you for reporting this - much appreciated!
> 
> Based on your description we've now reproduced this issue as a regression from v29.3.5.
> 
> This issue was fixed in v27.0, and is once again reproducible with AG Grid v30.0 (however only when using Angular).
> 
> We have added this bug to our backlog and we are tracking it with the following reference and description: **AG-8778 When using Angular, console warning is shown "Added non-passive event listener to a scroll-blocking 'wheel' event."**
> 
> We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
> 
> See whether this item will be part of our next release by checking the NEXT RELEASE checkbox on the product pipeline page: https://www.ag-grid.com/ag-grid-pipeline/
> 
> **Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version: https://www.ag-grid.com/ag-grid-changelog/**
> 
> Thanks again for bringing this up with us - we appreciate your time!

Sounds great, thank you for the update!
