### ISSUE TITLE
v13 ag-header-cell still has "colid" attr instead of "col-id"

### ISSUE THREAD

**Issue by ataft** [ag-grid/ag-grid#1845]
See here:
![image](https://user-images.githubusercontent.com/11670864/29747028-9d0f4df0-8aa1-11e7-8a4c-ca1c49b96b42.png)

Also, with pivots, how can we get the colDef or field id from the colid? For example, see the following grid with 2 pivoted columns:
![image](https://user-images.githubusercontent.com/11670864/29747152-c1b67ab8-8aa4-11e7-8790-ad98d78d27b1.png)

Of the highlighted columns, Group B has colid=pivot11_0, 2012-13 has colid=pivot14_0, and Total Discharges has colid=pivot_15. I can't make any sense of it.

For column headers, is there an event like cellClicked that gives you the node with all the attributes? I'd rather use that then the colid's from the element.

**Comment by ceolter** [comment]
noted. will fix.

**Comment by ceolter** [comment]
fixed. will be in todays release.

**Comment by ataft** [comment]
I'm not sure how this is possible, but "colid" still appears intermittently in my application, apparently when the class is "ag-header-cell-sorted-none". See below, there's a mix of "col-id" and "colid":

![image](https://user-images.githubusercontent.com/11670864/29948066-bb1a89a4-8e61-11e7-8af8-4c327f2065da.png)
