### ISSUE TITLE
ag-row-focus class getting applied to all rows on load

### ISSUE THREAD

**Issue by panicst8** [ag-grid/ag-grid#1865]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The ag-row-focus class seems to be applied to all rows as grid loads, as well as ag-row-no-focus.

**Expected behavior**

When the grid is loaded no rows should be focused, having this class:  ag-row-no-focus

**Minimal reproduction of the problem with instructions**

1. Set a style on ag-row-focus ( grid will load with style applied to all rows. )
2. click on a row to focus
3. use arrows to change focus up and down
4. You can see that the actual change of focus removes the class properly and then applies it properly just not on load.

https://plnkr.co/edit/iEvz7cqwMDWjUUT6YHIB?p=preview

**What is the motivation / use case for changing the behavior?**

Being able to highlight the focused row.

**Please tell us about your environment:**

Operating System: Windows 10
IDE: VS Code
Package Manager: yarn
HTTP Server: IIS Express

* **ag-Grid version:** 13.0.1

* **Browser:** "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

* **Language:** [ All ]

**Comment by panicst8** [comment]
created a pull request that seems to fix the issue:

FIX for issue #1865 - class 'ag-row-focus' getting applied to all rows on load
#1867 opened 2 minutes ago by panicst8

**Comment by petyosi** [comment]
Thank you, we will look into that.

**Comment by ceolter** [comment]
fixed. will be in next release. thanks.

**Comment by panicst8** [comment]
Just removing:  `classes.push('ag-row-no-focus');`   doesn't solve the issue you need the other line i changed in my pull request . which swaps the ternary logic, currently it says if the row is focused use 'ag-row-no-focus' .  and if not focused use 'ag-row-focus'.

**Current**:
  `classes.push(this.rowFocused ? 'ag-row-no-focus' : 'ag-row-focus');`

**Fixed**
  `classes.push(this.rowFocused ? 'ag-row-focus' : 'ag-row-no-focus');`

**Comment by jameswyse** [comment]
@ceolter This is broken in the latest release, every row now has `.ag-row-focus` on load!

**Comment by panicst8** [comment]
My fix above that was also in my pull request would fix it, as you can see the line checks to see if it is focused, then sets style to not focus, and if it is it sets it to not, and since no rows are focused out of gate, all rows are set to focused.  it works perfect after that if you click row then arrow up down it resumes correct behavior....  :-) I had to pull out focus style until fix is applied, which is breaking some functionality in my app :-( . Thanks for bringing attention.
