### ISSUE TITLE
Column menu button not showing in iPad

### ISSUE THREAD

**Issue by truetopwebghost** [ag-grid/ag-grid#2297]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
column menu button not showing Chrome and Safari in iPad evenif set suppressMenuHide = true
**Expected behavior**
column menu button should be displayed in iPad like in iPhone

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid version:** 17.0.0

* **Browser:**

`Mozilla/5.0 (iPad; CPU OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1`
* **Language:** [ES6]

**Comment by mohyeid** [comment]
Like what version this was fixed at? I think you needed to be specific.

**Comment by RohithKP** [comment]
> Hi,
> 
> In ag-grid we have recently started processing github issues as well as customer issues. We are also going through the backlog of issues already open and acting on them as necessary, on this particular case, it seems like this issue could be gone in our latest release.
> 
> Could you update the ag-grid version in your end and try again?
> 
> Note that this issue is getting closed, but you are welcomed to create a new issue if you think this issue is still not resolved
> 
> Thanks

@makinggoodsoftware the issue is still present https://plnkr.co/edit/qAoNUuL22XxPxgDg?preview

![eMenu-1](https://user-images.githubusercontent.com/8155276/88539872-a21be980-d02f-11ea-8a7b-e9d575959435.PNG)
