### ISSUE TITLE
horizontal scroll issues in RTL

### ISSUE THREAD

**Issue by reza3vi** [ag-grid/ag-grid#2914]
![image](https://user-images.githubusercontent.com/42288686/51787320-8e1ad180-2185-11e9-9a35-852c5af27855.png)

![image](https://user-images.githubusercontent.com/42288686/51787369-3892f480-2186-11e9-8461-6dc935fe2759.png)

![image](https://user-images.githubusercontent.com/42288686/51787375-4779a700-2186-11e9-8148-b556c89ccfd2.png)

some columns value not shown

**Comment by reza3vi** [comment]
Issuse just in chrome on rtl grid

**Comment by TrueMoein** [comment]
![hr-scroll](https://user-images.githubusercontent.com/7044050/51962025-fadae800-2473-11e9-8001-5dd7a7303de7.gif)

+1 Same issue...

**Comment by HyperComplex** [comment]
@TrueMoein i think i had your issue with ag grid version 18 on android devices and when google chrome 71 released the same problem happened in the desktop version too. this issue is fixed in version 19.1.1 [here](https://www.ag-grid.com/ag-grid-changelog/?fixVersion=19.1.1) key AG-2198, also ensure that you set enableRtl=true.

**Comment by reza3vi** [comment]
> ![hr-scroll](https://user-images.githubusercontent.com/7044050/51962025-fadae800-2473-11e9-8001-5dd7a7303de7.gif)
> 
> +1 Same issue...

man moshkel ro hal kardam, age khasti payam bede. telegram id @reza3vi

**Comment by reza3vi** [comment]
I fixed the problem. telegram id: @reza3vi

**Comment by gportela85** [comment]
@reza3vi The issue with Chrome not being detected on v71+ has been fixed on ag-Grid v20

**Comment by leibole** [comment]
This is still happening for, in version: "ag-grid-community": "^23.2.0".

Can you advice how to fix?
