### ISSUE TITLE
Extra Space is coming in every column while displaying checkbox dynamically in the first column

### ISSUE THREAD

**Issue by ankitsaini345** [ag-grid/ag-grid#3133]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

I am using this example [https://www.ag-grid.com/javascript-grid-selection/#example-header-checkbox-entire-set](https://www.ag-grid.com/javascript-grid-selection/#example-header-checkbox-entire-set) to display checkbox always in first column even if we change column position by drag and drop. 
The problem I am facing is shown in below screenshot

![image](https://user-images.githubusercontent.com/37847177/57770522-22597600-772e-11e9-8273-df252ee66841.png)

**Expected behavior**

Extra space should not be there.

![image](https://user-images.githubusercontent.com/37847177/57771155-8df01300-772f-11e9-867c-799979b06955.png)

**Please tell us about your environment:**

* **ag-Grid version:** 20.2.0

* **Browser:**

Chrome 72.0.3626.121 

* **Language:** [ TypeScript 3.2]

**Comment by raycashmore** [comment]
Same here. It's adding the checkbox to the dom (with display:none) to every single cell. Probably because of a bad falsey check if a function is used for the checkboxSelection property on a ColDef -even if it returns false.

**Comment by gportela85** [comment]
Fixed in the `latest` branch. Thanks for reporting

**Comment by ankitsaini345** [comment]
Hi @gportela85 ,

Thanks for update, so in which version we can expect this fix.

**Comment by gportela85** [comment]
@ankitsaini345 released today, so the example above should be fixed.

**Comment by AndreaEsposit** [comment]
I think this is still an issue on version 29.0.0. @gportela85. Is there a better way to have the checkbox always in the first column?
