### ISSUE TITLE
Ag-Grid Export To Excel with Style for Number is not working

### ISSUE THREAD

**Issue by SwapnilLomate** [ag-grid/ag-grid#3318]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I have decimals in data property such as -1087.23 or 344.65 or 22 and i wanted excel to format them as number with thousand separators and 2 decimal however even after using style it does not format them.

I have tried to open both exported excel sheet from your e.g. and my sample in notepad and here is how it looks:
Yours:
"<c r=\"A1031\" t=\"s\">
"<v>999</v>"
"</c>"
Mine:
"<c r=\"J71\" t=\"n\">
"<v>-62.5</v>"
"</c>"

So can you help me understand why is this not working.
I have shared the style i have used.
**Expected behavior**
It should format it as per number with 2 decimal and thousand separator , and decimal separator .
**Please tell us about your environment:**

* **ag-Grid version:** 21.1.1

* **Browser:**

* **Language:** [JS]
          
 excelStyles: [{
                    id: 'currencyFormat',
                    numberFormat: {
                        format: "#,##0.00"
                    }
                }, {
                    id: 'textFormat',
                    dataType: 'string'
                }, {
                    id: 'dateFormat',
                    dataType: 'dateTime',
                    numberFormat: {
                        format: 'yyyy-MM-dd;@'
                    }
                }, {
                    id: 'dateTimeFormat',
                    dataType: 'dateTime',
                    numberFormat: {
                        format: 'yyyy-MM-dd hh:mm:ss'
                    }
                }]

**Comment by gportela85** [comment]
this issue has been fixed in the latest branch, thanks for reporting

**Comment by SwapnilLomate** [comment]
Do you mean its available in which version, I have v21.1.1 and I still have the issue.

**Comment by gportela85** [comment]
It's patched in the latest branch so it will be fixed in the next release
