### ISSUE TITLE
Drag and Drop  doesn't work on IE11

### ISSUE THREAD

**Issue by kieeeeei** [ag-grid/ag-grid#3323]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://www.ag-grid.com/javascript-grid-drag-and-drop/
This page's demos are not woking on IE11

**Current behavior**
When I drag any row and move, the following log is output to the console.
"The object does not support the 'indexOf' property or method."

**Expected behavior**
Demo work well on IE11 like chrome and other browsers

* **ag-Grid version:**
21.1.0

* **Browser:**
IE11

**Comment by IndProgo** [comment]
Those demos aren't working on Firefox too

**Comment by gportela85** [comment]
fixed in the latest branch, thanks for reporting it

**Comment by IndProgo** [comment]
React examples  for drag & drop still don't work on Firefox. 
https://www.ag-grid.com/javascript-grid-drag-and-drop/

**Comment by gportela85** [comment]
@IndProgo Just tested with Firefox 69.0 for MacOS and it's working fine with React. Any example in particular? Operating system?

**Comment by IndProgo** [comment]
It's working now. Sorry, maybe something was cached
