### ISSUE TITLE
Custom React cell renderers flick when using ReactNext

### ISSUE THREAD

**Issue by dcjones1** [ag-grid/ag-grid#3458]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

See issue #3095 for the same problem. When using a custom React cell renderer with reactNext, there are noticeable flickers when columnDefs are updated as well as when scrolling. See the following plunkr. [https://plnkr.co/edit/KYWDBUbQs2oVSKtRkjBM?p=preview](https://plnkr.co/edit/KYWDBUbQs2oVSKtRkjBM?p=preview)

If you update the colDef by clicking the button, you'll see the cells flicker during update. If you disable reactNext, the flicker stops as well. Additionally, if you quickly scroll with reactNext, you can see inconsistencies/flickers that are not there with reactNext disabled.

In the application I'm working on, I was able to write a custom renderer in plain Javascript and this eliminates the flicker. However, the other components are too complex without using a React renderer. When scrolling, it's apparent that two of my columns are updating in a different way as the flicker is very visible.

**Expected behavior**

I would expect the React renderer to perform in the same manner as the plain JS renderer. It seems this is possible since the flickers do not occur with reactNext disabled.

* **ag-Grid version:** X.X.X
Ag-Grid: 21.2.2
React: 16.10.1

* **Browser:**
Chrome

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog.

This is the reference and summary of the relevant issue:

AG-3595 React - Data Change Can Result In Flicker

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by Fiorello** [comment]
Hi,
I found the same problem both in version 0.21.1 with the reactNext parameter, and with version 0.22.1.
In previous version, while in previous versions it worked perfectly.
My code:
```
recordNode.setData(data);
gridApi.redrawRows({ rowNodes: [recordNode] });
```
This generates a flick effect
![flick](https://user-images.githubusercontent.com/3278942/76077057-4aa5b000-5fa0-11ea-8128-01e4d3088d5f.gif)

Has anyone found a solution?

**Comment by gombek** [comment]
Up vote! Any news on that?
I have same issue after upgrading from v21 to v23. All cells that uses react component flickers with every rowData update.
I need a fix or at least some workaround for that.

I use ag-grid-enterprise.

**Comment by biels** [comment]
I have the same issue. Any fix or workaround?

Using:
"ag-grid-enterprise": "^23.2.1",
"ag-grid-react": "^23.2.1",

Using custom framework cell renderers

**Comment by surajd-10** [comment]
@biels I am facing the same issue with the version you have mentioned and with custom renderers. Did anyone find the solution to this?

**Comment by biels** [comment]
I still haven't found a solution. I'm also interested in this.

**Comment by surajd-10** [comment]
@biels I found the solution on this. Here are my observations and findings:

Whenever custom cell renderers are to be updated, ag-grid is destroying the component and later remounts it with updated value,  as a result we see the flickering. To prevent the cell renderer component from being destroyed,
We should implement **refresh** method inside cell renderer component. Refresh method will have conditional logic to identify when to update the component and it should have setState method to update the new value (As refresh method won't call render implicitly). For example:
refresh(){
   if(some condition){
      this.setState({...}),
      return true;
   }
   return false;
}
Try this out once.

**Comment by kiril-matev** [comment]
Hello all!

This issue filed earlier under AG-3595 is resolved.

ag-Grid has addressed this flickering issue by modifying the way the value is rendered when using Custom React cell renderers. You need to set an additional property on the agGridReact component to activate this. This approach is described in detail here:
https://www.ag-grid.com/react-fine-tuning/#react-cell-rendering

I've modified the original sample to implement the suggested approach and address this:
https://plnkr.co/edit/UW96mVu3aT9qhQ3Q

Please note that there's no more column flickering when you click the button above the grid and there's much less flickering when scrolling through the records as that destroys and creates new React cell renderer components. 

Please let us know if you have any further comments.

**Comment by biels** [comment]
@kiril-matev What about when flickering is caused by underlying data triggering a redraw, not by a columnDef change (to my understanding that is what you showcase in [plnkr.co/edit/UW96mVu3aT9qhQ3Q](plnkr.co/edit/UW96mVu3aT9qhQ3Q))
I've not been able to prevent cell renderer flickering using the disableStaticMarkup property from the docs either. (I'm using ag-grid v24.0.0)

@surajd-10 Mentions some refresh method in the cell renderer. I've not been able to get this called or seen any referece to it.

Am I missing something?

**Comment by oliver-hoff** [comment]
@biels try the following plunkr example: https://plnkr.co/edit/CLmtxmVyxdjOlltp

By simply adding the refresh method, my flickering problems went away.

**Comment by truongnm97** [comment]
Is there any solution for ag-Grid v22, this version seems don't have refresh method implement in component

**Comment by Fiorello** [comment]
The error that had been resolved on version 24, returned with version 25.
Anyone have a stable solution?

**Comment by jkillian** [comment]
Using AG Grid v26 and also seeing React cell renderers flickering a lot. Going to try to figure out a workaround, but would love it if the flickering didn't happen in the first place!

**Comment by kiril-matev** [comment]
Hi all,

Thanks for following up.

As part of AG Grid 26 we've made a number of changes to AG Grid rendering when using React. We're introducing a new rendering engine that is written purely in React. This means the entire AG Grid UI is now available in React and your React components (cell renderers, cell editors, etc) will interact directly with the rest of the AG Grid UI. This will improve rendering performance, simplify your component code and better support React-specific language constructs and concepts.

Please switch to the new React rendering engine to resolve these flickering issues. Please read how to use it (and its current limitations) here:
https://www.ag-grid.com/react-data-grid/reactui/

For the full list of improvements in AG Grid 26, please see here:
https://blog.ag-grid.com/whats-new-in-ag-grid-26/

**Comment by jkillian** [comment]
Hi @kiril-matev - I'm excited about the work to make AG Grid use React under the hood! Unfortunately, we and probably many others can't take advantage of that yet because [enabling `reactUI` causes React column header components to break](https://www.ag-grid.com/react-data-grid/reactui/#how-much-of-ag-grid-is-now-react-ui):

> When reactUi=true, the mechanism of using React inside the old AG Grid rendering engine is turned off. This means React components provided to areas of the grid not yet using React UI will not work. For example if you have a custom Header Component written in React, it will currently not work when reactUi=true.

**Comment by hothvictor** [comment]
> @biels try the following plunkr example: https://plnkr.co/edit/CLmtxmVyxdjOlltp
> 
> By simply adding the refresh method, my flickering problems went away.

May I ask how can you know there have a refresh method in useImperativeHandle?

**Comment by kiril-matev** [comment]
Hi @jkillian,

Thanks for bringing this up. This was only a limitation in the first versions of ReactUI.

As part of AG Grid 26.2, ReactUI rendering now fully supports all UI elements which are used across AG Grid - column filters, floating filters, tool panels, status bar, overlays and tooltip. We encourage you to start using ReactUI across all your AG Grids to deliver the improvements in performance and simplify your component code.

You can see samples showing all components making up AG Grid working with ReactUI here:
https://www.ag-grid.com/react-data-grid/reactui/#all-customisations-supported

Specifically, custom column headers are fully supported as shown here:
https://www.ag-grid.com/react-data-grid/reactui/#customising-headers

You can find out about all of the new features in AG Grid v26.2 here:
https://blog.ag-grid.com/whats-new-in-ag-grid-26-2/

Thanks for using AG Grid!

**Comment by Fiorello** [comment]
Hi, 
thanks for AG Grid 26, is amazing ;)
Many of flickering error is resolved in this version, just like documentation says, but i stil have similar issue in a treeTable with a grouped column  whit "innerRender" and groupDisplayType: 'custom'.

```              
{
   colId: 'main',
   pinned: true,
   lockPinned: true,
   suppressMenu: true,
   suppressMovable: true,
   resizable: false,
   sortable: false,
   showRowGroup: true,
   filter: false,
   cellRenderer: 'agGroupCellRenderer',
   cellRendererParams: {
      checkbox: () => isMultipleSelectionEnabled,
      suppressCount: true,
      suppressDoubleClickExpand: true,
      innerRenderer: 'radarNameCellRenderer',
      caseSuffix: t({ id: `case.entity.short` }),
   },
}
```
              
If i use the same component 'radarNameCellRenderer' as "cellRenderer" instead of 'agGroupCellRenderer', it not flick.
![flick](https://user-images.githubusercontent.com/3278942/152585683-bfc3e473-8692-431c-b601-40c4ab67d67a.gif)

Maybe 'agGroupCellRenderer' with 'innerRender' use the old render?
Has anyone found a solution?

**Comment by fcaballero** [comment]
Using AG Grid 26, flickering still happening, any idea what we can do to avoid this?

**Comment by Fiorello** [comment]
In my case, adding ‘reactUi’ to props resolve

**Comment by joelrbaranowski** [comment]
Still seeing this with version 27.1.0

**Comment by kiril-matev** [comment]
Hello @joelrbaranowski!

Please try to reproduce this issue with AG Grid v27.2, which we've recently released.

If the issue is still there in v27.2, please provide a sample to reproduce it.

**Comment by joelrbaranowski** [comment]
Thank for you response. After further debugging, it looks like this was not an ag-grid issue and instead was caused by https://next-auth.js.org/ and specifically the refetchOnWindowFocus as detailed in https://next-auth.js.org/getting-started/client which was triggering the cell renderers to rebuild and flicker. Setting that to false fixes it.

**Comment by kiril-matev** [comment]
Thank you for the update @joelrbaranowski  - I'm glad to hear you've now resolved this issue.

**Comment by bosepher** [comment]
This may be useful to someone else.
Still on v26.2, I had a flickering problem with a column having a custom cell renderer (renders a button).
I solved it by setting a field="id" to the cell with the custom renderer.

```
<AgGridColumn
  field="id"
  checkboxSelection={true}>
</AgGridColumn>
<AgGridColumn
  headerName="Details"
  field="id"
  filter={false}
  resizable={false}
  sortable={false}
  cellRenderer="btnCellRenderer"
  cellRendererParams={{
  onShowDetails(e, nodeData) {
    showDetails(nodeData)
  }
}}
>
```

I think the reasoning is, without a field value, when a change occurs in the grid, like a row being selected, the logic cannot know that the data hasn't changed, so it refreshes the cell.
