### ISSUE TITLE
Column with lockVisible is hidden when hidding all columns

### ISSUE THREAD

**Issue by Oram** [ag-grid/ag-grid#3463]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

1. Go to [Lock Visible Example ](https://www.ag-grid.com/javascript-grid-column-moving/#lock-visible-example).
2. Open any column menu (≡).
3. Go to column selection (|||).
4. Click the upper most checkbox (next to the filter text input).
5. All columns (even the ones that are defined with "lockVisible: true") are hidden.

**Expected behavior**
Lock visible columns should not change their visible state.

**ag-Grid version:**
I encountered the bug in 21.2.1.
According to the change log of 21.2.2 (latest) it was not fixed.

**Browser:**

FF: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
Chrome: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36"

**Comment by davis4acca** [comment]
Hi,

This has been fixed in v22.

Reference for this: AG-3421  LockVisible column can be hidden by toggling all columns from tool bar

**Comment by myklt** [comment]
Hi @davis4acca ,

Would it be possible to get those fixes in patch or minor release? Any workaround in case we cannot update to v22?

Thanks!

**Comment by MoistJohn** [comment]
Issue still exists.
Current behavior:
1. go to Go to [Lock Visible Example](https://www.ag-grid.com/javascript-grid-column-moving/#lock-visible-example)
2. Open any column menu (≡).
3. Go to column selection (|||).
3. Input in the column filtering "a" (which should still include all columns)
4. Click the upper most checkbox (next to the filter text input).
5. All columns will be hidden.

**Comment by icedjello** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

This is the reference and summary of the relevant issue:

AG- 3702 - REGRESSION: lockVisible breaks when filtering + select all checkbox is used
