### ISSUE TITLE
Why do I get unstable_flushDiscreteUpdates in AgGridReact [latest]

### ISSUE THREAD

**Issue by simkessy** [ag-grid/ag-grid#3680]
Why do I get this error when my grid updates? 

```

backend.js:6 Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering.
    in AgGridReact
    in div
```

**Comment by AhmedAGadir** [comment]
Hi,

ag-grid staff does not provide support through github. If you are a customer please contact us through our official support channel. Note that this issue has been flagged as managed-by-the-community, we also recommend you to check stackoverflow, note that if there is no activity on this issue after a while we will close it.

Thanks

**Comment by jackdh** [comment]
I've also recently been getting this.

**Comment by simkessy** [comment]
Don't worry, i'm sure we'll get a useful response from the devs soon.

**Comment by jackdh** [comment]
@AhmedAGadir I think we'd like to register this as a bug not as a support request. Please change the tag.

**Comment by rahul-sivalenka** [comment]
Same is the case with me. When I edit a cell using a custom react cell editor component I am getting the same error. Here's codesandbox for the same.

https://codesandbox.io/s/ag-grid-formik-fieldarray-integration-cjcie

**Comment by jackdh** [comment]
@AhmedAGadir any response?

**Comment by stephtea** [comment]
It seems like it's something to do with aggrid doing direct dom manipulation by the cell being edited outside of react lifecycle.

**Comment by seanlandsman** [comment]
@stephtea @jackdh @simkessy 

I'll take a look at this - @rahul-sivalenka your repo will be useful in determining the issue here

**Comment by MyCupOfTeaOo** [comment]
Same is the case with me.

**Comment by seanlandsman** [comment]
I'll be taking a look at this issue this week

**Comment by seanlandsman** [comment]
I'm looking at this issue now - does this warning cause actual issues in your application(s)? From the repo provided it doesn't appear to actually impact the normal working operation of it.

I'm not suggesting this isn't something that needs to be fixed but rather am trying to determine the seriousness of it.

thanks

**Comment by jackdh** [comment]
Hi @seanlandsman 

I've not actually seen any issues no

**Comment by simkessy** [comment]
Same

**Comment by mentierd** [comment]
I see it when I call a context method that updates the grid's rowData.

**Comment by stratospark** [comment]
@mentierd I see the same issue with context menu altering rowData. Any workarounds?

**Comment by Dbuggerx** [comment]
@AhmedAGadir, as you can see, this is happening for multiple devs, and **it's clearly a bug**. Maybe it doesn't affect the usage of AgGrid right now, but **could be very problematic in a new React version**. Could you please change it to a **bug** ?

**Comment by hinsenchan** [comment]
Hopefully this is helpful in case the `deltaRowDataMode` prop was missed. It was not obvious to me on my first implementation.

I got the `Warning: unstable_flushDiscreteUpdates` when I used `Redux` to supply data to the `rowData` prop. It was resolved by setting `deltaRowDataMode={true}` and `getRowNodeId={(data) => data.id}` as instructed in the documentation. It allows Ag-Grid to work with immutable data stores. Not sure if this is the same root cause that you guys are experiencing?  

https://www.ag-grid.com/javascript-grid-data-update/#delta-row-data

**Comment by seanlandsman** [comment]
@Dbuggerx this is being treated as bug and can be found on our pipeline under AG-4049 here: https://www.ag-grid.com/ag-grid-pipeline/

This is being looked at and I'll update this thread as soon as I have something to report. It is not being ignored!

**Comment by Dbuggerx** [comment]
Hey @seanlandsman, thanks for the reply!

**Comment by matgargano** [comment]
@seanlandsman I am seeing this issue when updating the state that controls my grid data after the `rowDragEnd` event. Does this sound like it's related to `AG-4049`

The error I receive is

```
index.js:1 Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering.
    in AgGridReact
```

Thanks for any help.

**Comment by seanlandsman** [comment]
@matgargano yes it does - if you have a repo I can use for this that would help too. The more I have the better to solve this

thanks

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs, and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-4049 | [React] ag-react-grid unable to update state after cell edit (Warning: unstable_flushDiscreteUpdates)

**Comment by SV-Mahesh** [comment]
Any Update on this issue?

**Comment by flocbit** [comment]
In my case this issue appears in console when editing pinned top row cells...

**Comment by seanlandsman** [comment]
@flocbit do you have a repo of this?

**Comment by flocbit** [comment]
I'm afraid I can't share my clients repo with you. I could send you some code samples though...?

**Comment by seanlandsman** [comment]
It doesn't have to be the full code - just something I can use to repro the issue and test any possible fix against - thanks!

**Comment by simkessy** [comment]
There's already a repo example in this thread. So was that issue ever addressed, because if it wasn't another repo doesn't give you anything additional.

**Comment by gerrod** [comment]
@seanlandsman here's a simple repro for you -

https://stackblitz.com/edit/react-tqf7fg?file=index.js

Just check/uncheck any of the checkboxes in any row and you'll see the problem appear in the console. I've tried this in Chrome and Edge (Chromium) and the warning appears for both of those - interestingly though it doesn't appear in Firefox.

Might be pushing my luck here, haha, but while you're there - try clicking any checkbox on and off really quickly on a single row, and you'll see all the checkboxes that are rendered by the functional component (`F/T (FC)` column) flickering while they're repainting. I've noticed this quite a lot with the grid - but if you use a class based component (`F/T (Class)` column) this doesn't happen... why is this?

**Comment by seanlandsman** [comment]
@gerrod thanks - this is helpful

**Comment by seanlandsman** [comment]
@simkessy I find multiple repos can occasionally be useful. If you don't theb that's fine too.

**Comment by mentierd** [comment]
@stratospark I ended up converting to use react context instead. I did notice that when upgrading to 21.1.2, that error seemed to go away.

Surprised they didn't close this yet. They usually feed you that BS line about this not being the correct spot to report a bug and then immediately close it.

**Comment by tolgaduzenli** [comment]
api.redrawRows()  can help you.  basically grid api should take care of re-render operation when you need to refresh the data.
[Explanation in here](https://www.ag-grid.com/javascript-grid-refresh/)

**Comment by Gofive** [comment]
> @simkessy I find multiple repos can occasionally be useful. If you don't theb that's fine too.
The issue will be fixed in the latest release v23.2.0 (5th Jun 2020)?

**Comment by yumindeckard** [comment]
Since it's a bug, not a new feature, will it also be fixed in older versions? We use v20.1.1 enterprise version. @Gofive

**Comment by ianbale** [comment]
I've only been using ag_grid today, but already run into this error message.

I am loading data into my grid incrementally. If I never click on the grid, then new data is added without error. But, if I have clicked on the grid (even if row / cell selection is disabled) then this error is thrown.

**Comment by JenRob17** [comment]
This is closed, however, we are Enterprise customers and still seeing this problem.  Was there a resolution?

**Comment by natejcho** [comment]
> This is closed, however, we are Enterprise customers and still seeing this problem. Was there a resolution? @seanlandsman

They closed it bc the issue is being tracked in their enterprise pipeline. 
https://www.ag-grid.com/ag-grid-pipeline/

search for ag-4049 and you'll see it's in the backlog currently

**Comment by mentierd** [comment]
@natejcho you guys should prioritize it; it's been an issue since 2018 for me

**Comment by CharlesMulic** [comment]
Also running in to this as an enterprise customer. +1 for prioritization.

**Comment by asherrna** [comment]
I have this issue when updating rowData directly, but not when updating rowData via the api.

**Comment by ed-workbase** [comment]
Adding another voice of an enterprise customer who is getting this.

**Comment by etyp** [comment]
Another Enterprise customer running into this issue here.

It's badly affecting our users as the custom editor dropdown appears and them immediately disappears, causing massive user frustration. We don't have a workaround and are completely stuck on how to patch this without changes from ag-Grid.

**Comment by cesarvargas00** [comment]
If you are using react with Redux, try checking [this part of the documentation](https://www.ag-grid.com/javascript-grid-immutable-data/).
This helped me a lot and now it is working perfectly ❤️

**Comment by alaarab** [comment]
Getting this even with immutableData={true} and getRowNodeId={(data) => data._id}

**Comment by maxLatoche** [comment]
enterprise customer here also dealing with this problem.

It manifests any time I try to update columnDefs in a React component.

I am using `immutableData={true}` and and `getRowNodeId={(data) => data._id}`. Everything works great until I try and add custom updates to columns.

[I've tried using declarative column definitions and I've tried binding columnDefs.](https://www.ag-grid.com/react-column-configuration/) When an event handler triggers an update to columnDefs in my application state, the new values are passed to the AgGridReact component, but updates don't propagate and `unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering` is thrown.  Subsequent rerenders (like after I update some rowData) propagate the columnDef changes to the DOM.  My understanding of the declarative API from the documentation linked is that both of these approaches are valid.

Are declarative updates to columnDefs supported in React at the moment?  Everything I can find in the docs only shows static data passed as columnDefs.  Digging into the source code further, it looks like columns are completely destroyed and recreated outside of the virtual DOM on each update.  This seems to be a fundamental problem without a workaround short of a fix of issue ag-4049.

**Comment by maxLatoche** [comment]
[I've recreated the problem of dynamically updating columnDefs here.](https://codesandbox.io/s/distracted-villani-lz2qr?file=/src/index.js)
1. Click on the 'toggle text wrap' button, which updates a flag in local state.  Text wrapping does not update in the DOM.
2. scroll to the right until the column is out of view, and has been removed from the DOM
3. scroll back to the left until the column is in view again.  Text wrapping is now in sync with the flag in local state.

**Comment by lauraalkhoury-varicent** [comment]
@seanlandsman any updates on this one? I don't see ag-4049 in the pipeline anymore

**Comment by seanlandsman** [comment]
@lauraalkhoury-varicent this has now been fixed - you can see it in our changelog here: https://www.ag-grid.com/ag-grid-changelog/?fixVersion=25.0.0

**Comment by readikus** [comment]
I am still experiencing this issue with `25.0.1`

**Comment by galleyrob** [comment]
Enterprise customer, version 26.2.0 and still getting this problem

**Comment by readikus** [comment]
I'm so glad I no longer am in a company that has to work with this horrific library.
