### ISSUE TITLE
Vue 3: params not available inside setup function

### ISSUE THREAD

**Issue by livthomas** [ag-grid/ag-grid#4645]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

If you modify [CellComponentRenderer](https://github.com/ag-grid/ag-grid-vue3-example/blob/97dd639da19e8f5a740c3669f7dd1b38c2ffed4f/src/rich-grid-example/CellComponentRenderer.vue) from [rich-grid-example](https://github.com/ag-grid/ag-grid-vue3-example/tree/master/src/rich-grid-example) and try to access `params` inside `setup` function, you will see it is always `undefined`:

```vue
<template>
    <span class="cell">{{ params.value }}</span>
</template>

<script lang="ts">
import {ICellRendererParams} from '@ag-grid-community/core';
import {defineComponent, watch} from 'vue';

export default defineComponent({
  name: 'CellComponentRenderer',
  setup(props) {
    const params = computed(() => (props as {params: ICellRendererParams}).params);

    console.log(params.value)
    watch(params, () => console.log(params.value));
  },
});
</script>

<style scoped>
.cell {
    color: blue;
}
</style>
```

Defining `params` as a prop don't help either:

```vue
<script lang="ts">
import {ICellRendererParams} from '@ag-grid-community/core';
import {defineComponent, PropType, watch} from 'vue';

export default defineComponent({
  name: 'CellComponentRenderer',
  props: {
    params: {
      type: Object as PropType<ICellRendererParams>
    }
  }
  setup(props) {
    console.log(props.params);
    watch(props, () => console.log(props.params));
  },
});
</script>
```

Vue will even start complaining in such case:

```
[Vue warn]: Data property "params" is already defined in Props.
```

**Expected behavior**

`params` property needs to be present in `props` parameter of `setup` function.

**Please tell us about your environment:**

* **AG Grid version:** 26.0.0

* **Browser:** Brave

* **Language:** TypeScript 4.3.5

* **Framework:** Vue.js 3.2.6

**Comment by seanlandsman** [comment]
Thanks for reporting - I'll investigate and update ASAP

**Comment by henrysuma** [comment]
I have the same problem, using:

Vue: 3.2.2 
Typescript: 4.3.5 
AG-Grid: 26.0.0

I have added a ObjectGridCustomHeaderCheckboxto headerComponentFramework and it is impossible for us to access params.api, inside the Component (using Composition API) to interact with (parent) Grid API.

Thanks.

**Comment by seanlandsman** [comment]
A fix for this is in progress - we'll be issuing a patch release next week to resolve this

**Comment by seanlandsman** [comment]
@livthomas @henrysuma 

I've published `26.0.1-beta.0` of both `@ag-grid-community/vue3` and `ag-grid-vue3` 

Let me know if this fixes the above issue for you! 

thanks

**Comment by seanlandsman** [comment]
I've published 26.0.1 of both @ag-grid-community/vue3 and ag-grid-vue3

Thanks for reporting this

**Comment by alexmccabe** [comment]
This wasn't fixed for Vue `2.7.xx`, I still get the same issue with AG Grid `27.3.0` 😔

**Comment by GabrielHangor** [comment]
> This wasn't fixed for Vue `2.7.xx`, I still get the same issue with AG Grid `27.3.0` 😔

Same...

**Comment by AG-Zoheil** [comment]
Hi

Thank you for your comment.

We'd be keen to look into this again, but as you can see this is quite an old issue from

The grid has naturally advanced a lot since then. If you are still having problems, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team support in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Much appreciated!

Kind regards,
Zoheil

**Comment by GabrielHangor** [comment]
I am on Vue 2.7xx and stick to options api via defineComponent when declaring my custom cell editors. This way, params are injected in data. So you can just work with the params property in data like it is a prop...Not so convenient but working

![image](https://github.com/ag-grid/ag-grid/assets/65975364/69c8090c-1025-4c3e-a555-6d5684ecfe1f)

**Comment by Dwhyte** [comment]
This is what I ended up doing for seeing the "params" inside a custom vue component

`<script setup>
const props = defineProps({
  params: {
    type: Object
  }
});
console.log(props.params);
</script>`

**Comment by rafacribas** [comment]
Accessing params inside a custom cell renderer using vue 2.7 is being a real challenge. I could not find any solution for it.

**Comment by VictorMeneghini** [comment]
Hello everyone!

I’m using Nuxt.js (Vue 2) with @vue/composition-api to enable the Composition API. I encountered the same issue with params not being reactive inside setup.

It's not the most elegant solution, but I ended up manually creating a Vue instance and passing the params as reactive props. This makes the component reactive, and while it's a bit hacky, it works really well in my project.

First, I created a help function to be able to reuse it in differents parts of my table:

**Util.ts**
```ts
import { reactive } from '@vue/composition-api';

function createReactiveRenderer(customComponent, initialProps) {
  const state = reactive({ ...initialProps });
  const el = document.createElement('div');

  const app = new (require('vue')).default({
    render: (h) => h(customComponent, { props: { ...state } }),
  });

  app.$mount();
  el.appendChild(app.$el);
  
  return el;
}
```

And then I finally can use it in ag-grid (30.x.x version):

**serverFileThatIUseToConfigMyTable.ts**
```ts
{
    field: 'fieldName',
    headerName: 'My column',
    cellRenderer: (params) => {      
      const reactiveValue = reactive({ text: params.value });
      return createReactiveRenderer(MyCustomComponent, reactiveValue);
    },
},
```

And I can use the props normally inside my Component

```vue
<template>
  <div 
    class="truncated-cell" 
    :title="text"
  >
    {{ text }} 
  </div>
</template>

<script lang="ts">
import { createComponent } from '@vue/composition-api'

export default createComponent({
  name: 'my-custom-component',
  props: {
    text: String
  },
  setups(props) {
    console.log(props) // {text: "prosp value (:"}  
   }
})
</script>
```

Remember, It’s just a temporary fix, and I’m monitoring the performance closely to ensure it doesn't cause any issues, but I wanted to share with you!
