### ISSUE TITLE
aria-description is not a valid attribute.Accessbility bug. Ag-grid version 28.2.1 react version V18

### ISSUE THREAD

**Issue by sindhuraN** [ag-grid/ag-grid#6297]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

**Expected behavior**

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by gportela85** [comment]
This issue has been fixed in the latest version of Ag Grid.

**Comment by sindhuraN** [comment]
@gportela85  - I have upgraded to the latest version of    "ag-grid-community": "^29.1.0",
    "ag-grid-react": "^29.1.0" but i still see the same issue. Could you please let me know in which version it is fixed

**Comment by kaiyoma** [comment]
I am also seeing this: https://github.com/ag-grid/ag-grid/issues/6684

**Comment by autumninflab** [comment]
version 29.3.5 also have this issue.

**Comment by mtpbzz** [comment]
Also still getting this

**Comment by kiril-matev** [comment]
Hi all,

Please send us a sample to reproduce this issue, so we can validate against the exact scenario you have.

Looking forward to your response.

**Comment by kiril-matev** [comment]
Hi all,

This isn't an issue with AG Grid.

This is caused by a known issue with React 17.x and earlier. Specifically, this is an issue with React Dev mode and this exception won't occur in prod mode.

Please see this logged for React here:
https://github.com/facebook/react/issues/21035

Here's the actual change in React 18 to fix this:
https://github.com/facebook/react/pull/22142

In order to fix this issue, please upgrade to React 18 or later.
