### ISSUE TITLE
V29.0.0 -> V29.2.0 Vertical Scrolling not working. V28.2.1 is fine.

### ISSUE THREAD

**Issue by sonicviz** [ag-grid/ag-grid#6467]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**

I've been using Community version 28.2.1 and it's been fine.
Just upgraded to V29.2.0 and noticed the sort is very slow to initiate, and also the vertical scroll on my pagination (80 rows per page) now doesn't work. 

I tested all versions again from V28.2.1 (working) and V29.0, V29.1, and V29.2

Vertical scrolling stops working and the vertical scroll bar doesn't show up from V29.0 onewards. 
Horizontal scrolling works, and the horizontal scroll bar shows up fine when I drag a column off screen. 

CSS was using the following in V28.2.1 just fine, with both vertical & horizontal scrollbars aok:

 .ag-body-viewport-wrapper.ag-layout-normal {
   overflow-x: scroll !important;
   overflow-y: scroll !important;
 }

 ::-webkit-scrollbar {
   -webkit-appearance: none;
   width: 8px;
   height: 8px;
 }

 ::-webkit-scrollbar-thumb {
   border-radius: 4px;
   background-color: #2CB1FF;
   box-shadow: 0 0 1px rgba(255, 255, 255, .5);
 }

Nothing in the release notes about scrolling related to this for V29.0

Any clues as to what I can look into to get the vertical scrolling back, like it was in V28.2.1

If I revert back to V28.2.1 paginated vertical scrolling is back just fine.

I'm assuming the vertical scrolling isn't working because the vertical scroll bar isn't showing, and possibly that's what triggers AG Grid vertical scroll? But unsure why the CSS working in V28.2.1 now doesn't work in V29.0.0

The slow sort reaction on column header clicking is puzzling as well, as in V28.2.1 it sorts virtually instantaneuously.
So perhaps something else is going on there too, but I couldn't see any breaking changes that were related to either issue. 

**Expected behavior**

Vertical scrolling with pagination should work as it does in V28.2.1

**Please tell us about your environment:**

Windows 11

* **AG Grid version:** X.X.X

Versions as described above. 

* **Browser:**

"Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/604.1.38 (KHTML, like Gecko) Chrome/49.0.2623 Safari/604.1.38 CoherentGT/2.0"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Javascript

**Comment by StephenCooper** [comment]
Hi @sonicviz,

I have the following example which has scrolling working in 29.2. Can you update this example to show your issue?

https://plnkr.co/edit/CzYCWKkbirzjoIjH?open=main.js

**Comment by sonicviz** [comment]
I'm not sure I'll be able to, but will have a play with it to see if I can replicate it.
The CSS is very different, as I explained in the OP. 

Thanks.

**Comment by StephenCooper** [comment]
I am guessing that you are not able to use the gridOptions properties for what you want to achieve?

https://ag-grid.com/javascript-data-grid/grid-options/#reference-scrolling

**Comment by sonicviz** [comment]
I use some of them already, but as mentioned, nothing was changed except for the library itself.

        this.gridOptions = {
            columnDefs: this.columnDefs,
            rowData: this.rowData,
            defaultColDef: { sortable: true, filter: true, editable: true, resizable: true },
            animateRows: true, // have rows animate to new positions when sorted
            icons: {
                // use font awesome for menu icons
            },

            getRowClass: params => {
                if (params.node.data.selected === true) {
                    return 'light-green-row';
                }
            },
            enableCellChangeFlash: true,
            allowShowChangeAfterFilter: true,
            cellFlashDelay: 250,
            cellFadeDelay: 500,
            singleClickEdit: true,
            stopEditingWhenCellsLoseFocus: true,
            alwaysShowHorizontalScroll: true,
            alwaysShowVerticalScroll: true,
            suppressMenuHide: true,
            tooltipShowDelay: 0,
            tooltipHideDelay: 2000,
            pagination: true,
            paginationPageSize: this.pageSize, 
            columnHoverHighlight: true,

            rowHeight: this.rowHeight,

            onSortChanged: params => {
                if (this.currentSelectedAircraft != null) {
                    this.resetSelectedPlane();
                }
            },
            onGridReady: params => {
                this.gridApi = params.api;
                this.columnApi = params.columnApi;
            },
            onFirstDataRendered: params => {

                this.gridApi.sizeColumnsToFit();

                if (this.currentSelectedAircraft != null) {
                    this.resetSelectedPlane();
                }
            },

**Comment by sonicviz** [comment]
I'm sure it's CSS related. 

If I use V29.2.0 with this CSS completely, which is key to getting scroll bars showing in V28.2.1, then I still see horizontal scroll bar, but lose the vertical.

If I remove this CSS completely I now also lose the horizontal scroll bar, replicating the vertical scrollbar loss issue. 

.ag-body-viewport-wrapper.ag-layout-normal {
  overflow-x: scroll !important;
  overflow-y: scroll !important;
}

::-webkit-scrollbar {
  -webkit-appearance: none;
  width: 8px;
  height: 8px;
}

::-webkit-scrollbar-thumb {
  border-radius: 4px;
  background-color: #2CB1FF;
  box-shadow: 0 0 1px rgba(255, 255, 255, .5);
}

**Comment by sonicviz** [comment]
The HTML/CSS is different with vertical scroll.

V28.2.1
https://imgur.com/7wJLuJe 

vs

V29.2.0
https://imgur.com/O0hthh5

**Comment by sonicviz** [comment]
Any tips on how I can get vertical scroll back, given how the HTML/CSS seems changed in V29.0+?
Are there some specific release notes you can point at that releate to this particular change, to get some more insight?

Thanks!

**Comment by StephenCooper** [comment]
I am not fully understanding the issue here. It sounds like you have written some custom css that was targeting the grid structure from v28 and now due to changes that custom css does not work anymore?

**Comment by sonicviz** [comment]
I didn't write it from scratch to get it working in V28.2.1

I used the solution here: https://github.com/ag-grid/ag-grid/issues/3226

**Comment by sonicviz** [comment]
For some reason the .ag-body-vertical-scroll-viewport overflow-y: scroll is now getting turned off, which is causing the vertical scroll to have the same size as the container, hence the scroll bar doesn't work correctly.

.ag-body-horizaontal-scroll-viewport overflow-x: scroll is working correctly, hence it shows ok.

**Comment by lsimeonov** [comment]
@sonicviz I had the exact same problem turned out I was importing non-existent CSS files from the old version

```
@import "ag-grid-community/src/styles/ag-grid.scss";
@import "ag-grid-community/src/styles/ag-theme-alpine/sass/ag-theme-alpine.scss";
```
I didn't had enough time to make a research but this is now working:

```
@import "ag-grid-community/styles/ag-grid.css";
@import "ag-grid-community/styles/ag-theme-alpine.css";
```

Hope it helps

**Comment by StephenCooper** [comment]
Closing as I believe this has been resolved now and was related to a particular app setup.

**Comment by sonicviz** [comment]
No, not resolved. Need to test with V30 to see if that resolves it.

**Comment by sonicviz** [comment]
Ok, I took another crack at updating with V1.30 and while it had the same issue I solved it, finally. 

For reference sake, in case anybody else has this issue (as other answers like use the nostyle and load CSS seperately didn't work):

As suspected, the solution was obviously simple in the end, but took some looking to figure out.

 I need overflow-y: auto !important; to get the vertical scroll bar to show, and was previously using
.ag-body-viewport-wrapper from V28.2.1 which no longer exists (maybe V1.29 changed it?) and is now just .ag-body.

/* Scrollbar fix*/
/* 
.ag-body-viewport-wrapper.ag-layout-normal {
  overflow-x: auto !important;
  overflow-y: auto !important;
}
 */
.ag-body.ag-layout-normal {
   overflow-x: auto !important;
   overflow-y: auto !important;
}

Maybe I missed it in the changes, but would be nice if css changes like that were obviously documented. 

On the plus side, V1.30 feels snappier and the new cell editors look useful!

Thanks.

**Comment by huangyuanzhen** [comment]
@sonicviz  @StephenCooper @lsimeonov  I also encountered the issue that vertical scroll bar shows empty space after I upgraded the ag-grid from V28 to V31.  
it can scroll but scroll bar shows empty space.
Could you please tell me how you fix the issue? Thank you very much. 

```
@import '~@ag-grid-community/styles/ag-grid.css';
@import '~@ag-grid-community/styles/ag-theme-balham.css';
```
![vertical](https://github.com/ag-grid/ag-grid/assets/15046044/5bf8cfd0-af17-40cd-9f8d-7b729515a411)

**Comment by sonicviz** [comment]
Solution for me was here: https://github.com/ag-grid/ag-grid/issues/6467#issuecomment-1599999587

Unfortunately I could never resolve another issue that occured with it https://github.com/ag-grid/ag-grid/issues/6794 so I'm stuck on V28
