### ISSUE TITLE
v30.0.0: Jest not working with ESM main.js

### ISSUE THREAD

**Issue by leandertolksdorf** [ag-grid/ag-grid#6766]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**
With Jest v26, a test importing for example "ClientSideRowModel" fails because Jest can't handle the new ESM main.js:

```
 FAIL  src/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /project/home/leandertolksdorf/workspace/src/index.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { x } from ".";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
```

**Expected behavior**
The test works like before

* **AG Grid version:** 30.0.0

**CodeSandbox:** https://codesandbox.io/p/sandbox/charming-elgamal-hgkmfr

**Comment by seanlandsman** [comment]
AG Grid by default now exports ESM ES6 (instead of CommonJS) - please see the [changelog](https://www.ag-grid.com/archive/30.0.0/changelog/ here:
)

If you add this to your `jest.config.js` it'll skip transforming AG Grid libraries:

```
module.exports = {
  transformIgnorePatterns: ['node_modules/(?!(@ag-grid-community.*)/)']
}
```

**Comment by ryanabaker** [comment]
> transformIgnorePatterns: ['node_modules/(?!(@ag-grid-community.*)/)']

When I add this to my project, it makes the test time go up significantly, and makes the tests flakey. Why would skipping transformation of this module cause this?

**Comment by seanlandsman** [comment]
@max-justice if you can provide a repo of what you're seeing I can take a look

@ryanabaker I'm afraid I don't know - that seems like a question for the jest team. If anything  I'd imagine the tests would run faster as they're processing less information

**Comment by ryanabaker** [comment]
Hm ok. Thanks for the response

**Comment by leandertolksdorf** [comment]
@ryanabaker @seanlandsman 
Isn't ignoring everything except @ag-grid-community/* what we want?
So that AGGrid are NOT being ignored from the transformation?

**Comment by ryanabaker** [comment]
> @ryanabaker @seanlandsman 
> Isn't ignoring everything except @ag-grid-community/* what we want?
> So that AGGrid are NOT being ignored from the transformation?

Yup, I believe this pattern is correct, and this is the desired behaviour. We want to only transform Ag-grid, nothing else. 

My tests pass locally when using the ignore pattern above, just when they get to the build server the build is flakey.

**Comment by fkul** [comment]
Hey, I'm also having issues with my `jest` tests:
```
    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /***/node_modules/ag-grid-react/lib/agGridReact.js:2
    import React, { Component } from 'react';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```
`transformIgnorePatterns` is not helping.

`ag-grid`: 30.0.2 (enterprise)
`jest`: 29.5.0
Test environment: `jsdom`

I'd be grateful for suggestions.

**Comment by sscaff1** [comment]
This ended up working for me:
```
  transformIgnorePatterns: [
    '/node_modules/(?!(ag-grid-react|ag-grid-enterprise|ag-grid-community)/)',
  ],
  ```
You may also need to specify the transformer to use:
```
  transform: {
   // in the case of the typescript - note the mjs
    '\\.(ts|tsx|mjs)?$': [
      'ts-jest',
      {
        diagnostics: false,
      },
    ],
    // in the case that you're using javascript with babel - note the mjs
    '\\.(js|jsx|mjs)$': 'babel-jest',
  },
  ```

the resolver in the options doesn't work. I don't think you can rely on every 3rd party package out there being build in a consistent manner with consistent configs for the package.json.

**Comment by smallbee3** [comment]
@sscaff1
Thanks a lot! It worked for me as well.
I was finally able to fix Jest's error `SyntaxError: Cannot use import statement outside a module`.

<br>

Here is my code:

_jest.config.js (or jest.config.cjs with ESM)_
```diff
module.exports = {
  ...
  transform: {
-   '^.+\\.(ts|tsx|js|jsx)$': [
+   '^.+\\.(ts|tsx|js|jsx|mjs)$': [
      'ts-jest',
      {
        diagnostics: false,
      },
    ],
  },
  transformIgnorePatterns: [
-   'node_modules/(?!(@ag-grid-community.*)/)',
-   '/node_modules/(?!(ag-grid-react|ag-grid-enterprise|ag-grid-community)/)',
+   '/node_modules/(?!(@ag-grid-community|@ag-grid-enterprise|ag-grid-react|ag-grid-enterprise|ag-grid-community)/)',
  ],
};
```

Notice that you should write ag-grid packages with one line in the `transformIgnorePatterns` unlike the suggestion in the official "AG Grid Changelog"
 page. Otherwise, you will face a `SyntaxError: Cannot use import statement outside a module` error.


<img width="771" alt="image" src="https://github.com/ag-grid/ag-grid/assets/35122143/d1726a78-26ac-4f10-8d57-5c918405c19b">

_https://www.ag-grid.com/changelog/_

**Comment by seanlandsman** [comment]
We have just released 30.0.6 : please see [ES Modules & CommonJS](https://blog.ag-grid.com/ag-grid-es-modules-and-commonjs/) for more information

**Comment by leandertolksdorf** [comment]
Unfortunately still not working on my project.

```
 ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { ClientSideRowModelModule } from "./clientSideRowModelModule.mjs";
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'
```

My jest config:
```
"preset": "ts-jest",
    "transform": {
      "^.+\\.(ts|tsx|js|jsx|mjs)$": [
        "ts-jest"
      ]
    },
    "transformIgnorePatterns": ["/node_modules/(?!(@ag-grid-community|@ag-grid-enterprise)/)"],
    "resetMocks": true,
    "setupFilesAfterEnv": [],
    "reporters": [
      "<rootDir>/src/test/frontend/reporters/suppress-log-spam-reporter.js",
      [
        "jest-junit",
        {
          "outputName": "target/junit-frontend.xml"
        }
      ]
    ],
    "moduleNameMapper": {
      "\\.(css|scss)$": "<rootDir>/src/test/frontend/mocks/styleMock.js",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/src/test/frontend/mocks/fileMock.js"
    }
```

**Comment by seanlandsman** [comment]
if you're able to provide a repo of this I'd be happy to take a look

**Comment by leandertolksdorf** [comment]
@seanlandsman I managed to create a sandbox reproducing this error:
https://codesandbox.io/p/sandbox/compassionate-panna-sfnv5g

**Comment by seanlandsman** [comment]
Thanks - that helps

I've taken a look at it seems that `ts-test` processes things a bit differently so you'll need to do the following:

jest.config.js

```
/** @type {import('jest').Config} */
module.exports = {
  preset: "ts-jest",
  resetMocks: true,
  setupFilesAfterEnv: [],
  resolver: '<rootDir>/myResolver.ts',
  transform: {
    "^.+\\.(ts|tsx|js|jsx|mjs)$": [
        "ts-jest"
    ],
  }
};
```

new file: myResolver.ts

```
module.exports = (request, options) => {
    return options.defaultResolver(request, {
        ...options,
        packageFilter: pkg => {
            const packageName = pkg.name;
            const agDependency = packageName.startsWith("@ag-grid");
            return {
                ...pkg,
                // default to use the CommonJS ES5 entry point for Jest testing with AG Grid
                main: agDependency ? './dist/cjs/es5/main.js' : pkg.module || pkg.main,
            };
        },
    });
};
```

**Comment by seanlandsman** [comment]
If you're using CRA you can try the following in your package.json (the config above won't be picked up)

```
"test": "react-scripts test --transformIgnorePatterns \"/node_modules/(?!(@ag-grid-community|@ag-grid-enterprise)/)\"",
```
