### ISSUE TITLE
Make ES5 CommonJS artefacts default again in ag-grid 30

### ISSUE THREAD

**Issue by ryanabaker** [ag-grid/ag-grid#6821]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Please tell us about your environment:**

* **AG Grid version:** 30.0.2

Hi, I recently upgraded to ag-grid v30 and am having trouble with build stability issues due to Jest and transforming the new ES6 ESM modules which are default in ag-grid v30 as stated in the changelog.

`In previous releases the main field of package.json defaulted to ES5 CommonJS artefacts. From v30 onwards the default will be ES6 ES Modules.`

I am looking for a way to default back to the ES5 CommonJS artefacts since the new ES6 ES Modules do not play nicely with Jest. I have added the `transformIgnorePattern` suggested in the changelog and [here](https://github.com/ag-grid/ag-grid/issues/6766), but I am running into memory issues on my build server (which I do not have control of)

Aside from going into the `node_modules` folder and manually changing the `package.json` of all the ag-grid modules such as `node_modules/@ag-grid-community/core/package.json` back to what it was before ag-grid 30, I have not found a way of going back to the ES5 CommonJS artefacts.

Any help is much appreciated!

**Comment by spamshaker** [comment]
similar issue here https://github.com/ag-grid/ag-grid/issues/6819
check the workaround provided here https://github.com/vitest-dev/vitest/issues/3688#issuecomment-1612043130

**Comment by ryanabaker** [comment]
> similar issue here #6819 check the workaround provided here [vitest-dev/vitest#3688 (comment)](https://github.com/vitest-dev/vitest/issues/3688#issuecomment-1612043130) initially problem reported here #4986

Hmm, I am using Angular, so the import that is giving me troubles is 

`import { AgGridModule } from '@ag-grid-community/angular';`

I've tried this, but am still getting error messages

`import { AgGridModule } from '@ag-grid-community/angular/lib/ag-grid-angular.module';`

**Comment by seanlandsman** [comment]
We'll be issuing a patch for this shortly - I'll update this thread accordingly.

**Comment by seanlandsman** [comment]
Release 30.0.3 has been released which should resolve this issue.

thanks

**Comment by ryanabaker** [comment]
> Release 30.0.3 has been released which should resolve this issue.
> 
> thanks

I'll try it out! Thanks alot!

**Comment by ryanabaker** [comment]
Thanks for the help! This worked! It allowed me to remove the `transformIgnorePatterns`. 

I still had build issues, but it was because I am using Nx, and the resolver listed here https://ag-grid.com/angular-data-grid/testing/ was overwriting the default Nx resolver.

Merging the two together works 😄

**Comment by georgiee** [comment]
@ryanabaker 
Thanks for putting both parts (Nx & AG Grid) in context.

I found the snippet in an issue and not in the documentation. Probably that was the origin.
https://github.com/ag-grid/ag-grid/issues/6828#issuecomment-1618391189

Regarding your comment of merging the two resolvers:
> Merging the two together works 😄

Do you have a matching code snippet how you did that? Because the same things happens for me.
The nx resolver is located here https://github.com/nrwl/nx/blob/7c76888cf0720bdce58a3cec6518fe73350a00ee/packages/jest/plugins/resolver.ts. Did you took their try-catch pattern to include the ag-grid specific resolver first and fall back to the nx resolver?

I've also another note: The resolver code is tied to the scoped packages (`@ag-grid`). The complete packages ( `ag-grid-community`) without the scope do not work with that as they use a different `dist/` folder structure.

The cjs files are not collected inside `dist/cjs` and they have different names. So we need to map main to `main: './dist/ag-grid-community.cjs.js` in this case. Probably we need a differentiation between `packageName.startsWith("ag-grid")` and `packageName.startsWith("@ag-grid")` to make the resolver work?

I would also expect ag grid to maintain and distribute such a resolver (similar to how nx includes a resolver)
The resolver also makes the transformation not necessary anymore it seems. I can confirm this.

I'm grateful for all the work put into ESM and the future but the jest vs Ag Grid thing seems only partially solved. Maybe @seanlandsman can chime in to clarify the current state? Do you have any more plans regarding the jest vs esm issues introduced with v30 or do you rely on the community to shape the topic? Thank you for any clarification 🙏

---

FYI. That's the `ag-grid-community` resolver working (⚠️ some parts redacted) but tests are still failing because of the missing nx specific resolver.

```
module.exports = (request, options) => {
    return options.defaultResolver(request, {
        ...options,
        packageFilter: pkg => {
            /*...*/
            const agDependency = packageName.startsWith("@ag-grid") || packageName.startsWith("ag-grid");
            return {
                ...pkg,
                // 👇 different path for the non scoped ag-grid package
                main: agDependency ? './dist/ag-grid-community.cjs.js' : pkg.module || pkg.main,
            };
        },
    });
};
```


<details>
<summary> Original Resolver </summary>

```
module.exports = (request, options) => {
    return options.defaultResolver(request, {
        ...options,
        packageFilter: pkg => {
            const packageName = pkg.name;
            if(packageName === '@ag-grid-community/angular' || packageName === 'ag-grid-angular') {
                return {
                    ...pkg,
                };
            }
            const agDependency = packageName.startsWith("@ag-grid") || packageName.startsWith("ag-grid");
            return {
                ...pkg,
                // default to use the CommonJS ES5 entry point for Jest testing with AG Grid
                main: agDependency ? './dist/cjs/es5/main.js' : pkg.module || pkg.main,
            };
        },
    });
};

```
</details>

**Comment by ryanabaker** [comment]
> @ryanabaker Thanks for putting both parts (Nx & AG Grid) in context.
> 
> I found the snippet in an issue and not in the documentation. Probably that was the origin. [#6828 (comment)](https://github.com/ag-grid/ag-grid/issues/6828#issuecomment-1618391189)
> 
> Regarding your comment of merging the two resolvers:
> 
> > Merging the two together works 😄
> 
> Do you have a matching code snippet how you did that? Because the same things happens for me. The nx resolver is located here https://github.com/nrwl/nx/blob/7c76888cf0720bdce58a3cec6518fe73350a00ee/packages/jest/plugins/resolver.ts. Did you took their try-catch pattern to include the ag-grid specific resolver first and fall back to the nx resolver?
> 
> I've also another note: The resolver code is tied to the scoped packages (`@ag-grid`). The complete packages ( `ag-grid-community`) without the scope do not work with that as they use a different `dist/` folder structure.
> 
> The cjs files are not collected inside `dist/cjs` and they have different names. So we need to map main to `main: './dist/ag-grid-community.cjs.js` in this case. Probably we need a differentiation between `packageName.startsWith("ag-grid")` and `packageName.startsWith("@ag-grid")` to make the resolver work?
> 
> I would also expect ag grid to maintain and distribute such a resolver (similar to how nx includes a resolver) The resolver also makes the transformation not necessary anymore it seems. I can confirm this.
> 
> I'm grateful for all the work put into ESM and the future but the jest vs Ag Grid thing seems only partially solved. Maybe @seanlandsman can chime in to clarify the current state? Do you have any more plans regarding the jest vs esm issues introduced with v30 or do you rely on the community to shape the topic? Thank you for any clarification 🙏
> 
> FYI. That's the `ag-grid-community` resolver working (⚠️ some parts redacted) but tests are still failing because of the missing nx specific resolver.
> 
> ```
> module.exports = (request, options) => {
>     return options.defaultResolver(request, {
>         ...options,
>         packageFilter: pkg => {
>             /*...*/
>             const agDependency = packageName.startsWith("@ag-grid") || packageName.startsWith("ag-grid");
>             return {
>                 ...pkg,
>                 // 👇 different path for the non scoped ag-grid package
>                 main: agDependency ? './dist/ag-grid-community.cjs.js' : pkg.module || pkg.main,
>             };
>         },
>     });
> };
> ```
> 
> Original Resolver

Here is the resolver that ended up working for me. Hope this helps!

Please note the comment at the top of this file for the default NX resolver (the one you linked is the TS one, this is the transpiled JS one)

```
/*
 * This is a custom resolver which steals nx implementation of the Jest resolver
 * and adds in the functionality for @ag-grid
 * Default nx resolver https://github.com/nrwl/nx/blob/master/scripts/patched-jest-resolver.js
 * Ag Grid resolver https://ag-grid.com/angular-data-grid/testing/
 */
'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
const path_1 = require('path');
const ts = require('typescript');
const fs = require('fs');
const { relative, join } = require('path');

/**
 * Custom resolver which will respect package exports (until Jest supports it natively
 * by resolving https://github.com/facebook/jest/issues/9771)
 */
const enhancedResolver = require('enhanced-resolve').create.sync({
  conditionNames: ['require', 'node', 'default'],
  extensions: ['.js', '.json', '.node', '.ts', '.tsx'],
});

function getCompilerSetup(rootDir) {
  const tsConfigPath =
    ts.findConfigFile(rootDir, ts.sys.fileExists, 'tsconfig.spec.json') ||
    ts.findConfigFile(rootDir, ts.sys.fileExists, 'tsconfig.test.json') ||
    ts.findConfigFile(rootDir, ts.sys.fileExists, 'tsconfig.jest.json');
  if (!tsConfigPath) {
    console.error(`Cannot locate a tsconfig.spec.json. Please create one at ${rootDir}/tsconfig.spec.json`);
  }
  const readResult = ts.readConfigFile(tsConfigPath, ts.sys.readFile);
  const config = ts.parseJsonConfigFileContent(readResult.config, ts.sys, path_1.dirname(tsConfigPath));
  const compilerOptions = config.options;
  const host = ts.createCompilerHost(compilerOptions, true);
  return { compilerOptions, host };
}
let compilerSetup;

if (process.argv[1].indexOf('jest-worker') > -1 || (process.argv.length >= 4 && process.argv[3].split(':')[1] === 'test')) {
  const root = path_1.join(__dirname, '..', 'tmp', 'unit');
  try {
    if (!fs.existsSync(root)) {
      fs.mkdirSync(root);
    }
  } catch (_err) {}
  process.env.NX_WORKSPACE_ROOT_PATH = root;
}

module.exports = function (path, options) {
  if (path === 'jest-sequencer-@jest/test-sequencer') return;
  const ext = path_1.extname(path);
  if (ext === '.css' || ext === '.scss' || ext === '.sass' || ext === '.less' || ext === '.styl') {
    return require.resolve('identity-obj-proxy');
  }
  // Try to use the defaultResolver
  try {
    if (path.startsWith('@nx/')) throw new Error('custom resolution');
    if (path.startsWith('nx/')) throw new Error('custom resolution');

    if (path.indexOf('@nx/workspace') > -1) {
      throw new Error('Reference to local Nx package found. Use local version instead.');
    }

    if (!(path.startsWith('@ag-grid-community/angular') || path.startsWith('ag-grid-angular')) && path.startsWith('@ag-grid')) {
      path += '/dist/cjs/es5/main.js';
    }

    console.log(path);

    // Global modules which must be resolved by defaultResolver
    if (['child_process', 'fs', 'http', 'path'].includes(path)) {
      return options.defaultResolver(path, options);
    }

    return enhancedResolver(options.basedir, path);
  } catch (e) {
    // Fallback to using typescript
    compilerSetup = compilerSetup || getCompilerSetup(options.rootDir);
    const { compilerOptions, host } = compilerSetup;

    // TODO(v17): Remove this workaround
    // We have some weird d.ts + .js business going on for these 2 imports so this is a workaround
    if (path === '@nx/devkit') {
      return join(__dirname, '../', './packages/devkit/index.js');
    } else if (path === '@nx/devkit/testing') {
      return join(__dirname, '../', './packages/devkit/testing.js');
    }
    return ts.resolveModuleName(path, join(options.basedir, 'fake-placeholder.ts'), compilerOptions, host).resolvedModule.resolvedFileName;
  }
};

```

The only line I added above is the following

```
    if (!(path.startsWith('@ag-grid-community/angular') || path.startsWith('ag-grid-angular')) && path.startsWith('@ag-grid')) {
      path += '/dist/cjs/es5/main.js';
    }
```

**Comment by georgiee** [comment]
Hey thanks for your quick reply!
Just in this moment I came to provide my solution because it was nagging so much that I wanted to solve it. Maybe interesting for you because I did not bother to cherry pick compiled files but imported the content - although I see where you're coming from 💪 

As said this works for the non scoped packages so probably revert the changes around `main: `./dist/${pkg.name}.cjs.js`.


```
// file: ag-grid-resolver.js in the Nx Workspace Root
const nxResolver = require('@nrwl/jest/plugins/resolver');

/**
 * AG Grid v30 introduced ESM packages which jest can't handle.
 * Jest relies on commonjs packages so we need to treat ag grid packages differently.
 *
 * References:
 * https://github.com/ag-grid/ag-grid/issues/6821#issuecomment-1621326081
 * https://github.com/ag-grid/ag-grid/issues/6821
 * https://github.com/ag-grid/ag-grid/issues/6766
 * https://www.ag-grid.com/javascript-data-grid/testing/
 */
const agResolve = (request, options) => {
  return options.defaultResolver(request, {
    ...options,
    packageFilter: (pkg) => {
      const packageName = pkg.name;
      if (
        packageName === '@ag-grid-community/angular' ||
        packageName === 'ag-grid-angular'
      ) {
        return {
          ...pkg
        };
      }
      const agDependency =
        packageName.startsWith('@ag-grid') || packageName.startsWith('ag-grid');

      if (agDependency) {
        return {
          ...pkg,
          // default to use the CommonJS ES5 entry point for Jest testing with AG Grid
          main: `./dist/${pkg.name}.cjs.js`
        };
      }
      
      // return unmodified if nothing matched, 
      // prevents main fields populated with undefined values (which fails for some scenarios  
      return pkg;
    }
  });
};

module.exports = (request, options) => {
  try {
    return agResolve(request, options);
  } catch {
    return nxResolver(request, options);
  }
};

```


Usage in the Nx Workspace. 
I put it in the root preset, as an alternative on a per project basis by using the project's jest config files.

```
// file: jest.preset.js

const nxPreset = require('@nx/jest/preset').default;
const path = require('path');

module.exports = {
  ...nxPreset,
  resolver: path.resolve(__dirname, 'ag-grid-resolver.js')
};
```

**Comment by yuchuan1** [comment]
@nrwl/jest has been renamed to [@nx/jest](https://www.npmjs.com/package/@nx/jest).
I have changed ag-grid-resolver.js to use
```
const nxResolver = require('@nx/jest/plugins/resolver');
```

**Comment by max-justice** [comment]
@georgiee thank you very much for your solution. was exactly what fixed the issue in my case as well

**Comment by sscaff1** [comment]
Can someone please explain why ag-grid decided on this feature? 

![Screenshot 2023-07-14 at 1 32 58 PM](https://github.com/ag-grid/ag-grid/assets/1554424/d3918fcb-39d9-4d43-8875-b0f44e3585b0)

who requested this? Why? This isn't a feature. This is bad module practice. 

https://github.com/ag-grid/ag-grid/blob/latest/grid-packages/ag-grid-community/package.json#L5-L6

module is correct here. Main should point to the commonjs file. 

Why do I have to have additional configs to test ag-grid? it makes no sense.

**Comment by seanlandsman** [comment]
We have just released 30.0.6 : please see [ES Modules & CommonJS](https://blog.ag-grid.com/ag-grid-es-modules-and-commonjs/) for more information

**Comment by robertIsaac** [comment]
I used @georgiee comment to generate this script for scoped packages

```
const path = require('path');
const nxResolver = require('@nrwl/jest/plugins/resolver');

/**
 * AG Grid v30 introduced ESM packages which jest can't handle.
 * Jest relies on commonjs packages so we need to treat ag grid packages differently.
 *
 * References:
 * https://github.com/ag-grid/ag-grid/issues/6821#issuecomment-1621326081
 * https://github.com/ag-grid/ag-grid/issues/6821
 * https://github.com/ag-grid/ag-grid/issues/6766
 * https://www.ag-grid.com/javascript-data-grid/testing/
 */
const agResolve = (request, options) => {
  return options.defaultResolver(request, {
    ...options,
    packageFilter: (pkg) => {
      const packageName = pkg.name;
      if (packageName === '@ag-grid-community/angular' || packageName === 'ag-grid-angular') {
        return {
          ...pkg,
        };
      }
      const agDependency = packageName.startsWith('@ag-grid') || packageName.startsWith('ag-grid');

      if (agDependency) {
        const filename = packageName.split('/')[1];
        const packagePath = path.join(
          __dirname,
          `../../node_modules/${packageName}/dist/${filename}.cjs.js`,
        );
        return {
          ...pkg,
          // default to use the CommonJS ES5 entry point for Jest testing with AG Grid
          main: packagePath,
        };
      }

      // return unmodified if nothing matched,
      // prevents main fields populated with undefined values (which fails for some scenarios
      return pkg;
    },
  });
};

module.exports = (request, options) => {
  try {
    return agResolve(request, options);
  } catch {
    return nxResolver(request, options);
  }
};
```

this works finally

**Comment by dmytro-afonin** [comment]
Didn't work for me.. still getting `Class constructor VanillaFrameworkOverrides cannot be invoked without 'new'`
Any idea why is this happening?
Got angular 16.2.11, ag-grid 30.2.0
