### ISSUE TITLE
React19beta and 'ResizeObserver': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by rbox-risk** [ag-grid/ag-grid#7948]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

In preparation for React19, as per most recent announcement from React, app developers should use `react@18.3.1`
https://react.dev/blog/2024/04/25/react-19-upgrade-guide
while feedback is obtained from library maintainers on react@19.0.0-beta

While testing on next.js, 
react@19.0.0-beta-4508873393-20240430 became a peer dependency from 14.3.0-canary.45 and onwards.

at which point the `ResizeObserver` bug appears in ag-grid. 
Reproduction below using most recent next@canary

https://codesandbox.io/p/github/rbox-risk/agv2-react19beta/main?import=true

To see the code working simply `pnpm add next@14.3.0-canary.44`

While not technically a bug for current non-beta releases, this may become a bug upon the release of react@19

**Current behavior**
Any use of AG-grid exits with fatal error:
`TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.`

(A similar situation for `ResizeObserver` happened during the pre-release of React18)

**Expected behavior**
No fatal error

**Please tell us about your environment:**
React

* **AG Grid version:** X.X.X
31.3.1

* **Browser:**
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6/7

**Comment by AG-Zoheil** [comment]
Update: We have released initial support for React 19 Beta as part of AG Grid v32.2.

https://blog.ag-grid.com/whats-new-in-ag-grid-32-2/

Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11651**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by nileriver2323** [comment]
Are there any updates on the status of this? Currently can't do any AG Grid development on a new project as it is using React 19.

**Comment by StephenCooper** [comment]
As a first step, could you confirm if you turn off Strict Mode do you still get the error. 

I believe the issue relates to changes in Strict Mode.

**Comment by rbox-risk** [comment]
Thanks Stephen - Yes I took the original example and amended `next.config.mjs` with 
```
const nextConfig = {
  reactStrictMode: false,
}

and the page loads

**Comment by StephenCooper** [comment]
In terms of a rough timeline it's unlikely React 19 support will land in v32 which is soon to be released. However, I would hope we would have things resolved for v32.1 which may still be released before React 19 moves out of beta. 

Do update this ticket if you find any other issues even when running without strict mode.

**Comment by maha-ghoneim** [comment]
the issue still exists with me after upgrading to version 32.1.0.

**Comment by StephenCooper** [comment]
Due to the changes still being made to React 19 we have decided to hold off landing the React 19 changes until it is released. 

So until then if you wish to use the beta versions of React 19 with AG Grid you will need to disable strictmode.

**Comment by StephenCooper** [comment]
**Update:** We have released initial support for React 19 Beta as part of AG Grid v32.2. 

https://blog.ag-grid.com/whats-new-in-ag-grid-32-2/

**Comment by paveg** [comment]
I'm trying to use a 32.3.3 or higher version of ag-grid with react v19 and If I configure StrictMode then the app is broken, so this problem seems to still exist.
What should I do about this?

**Comment by Amritpd** [comment]
Yeah this is still not working with the latest version of React (19) even with a fresh install.

**Comment by StephenCooper** [comment]
@Amritpd Can you provided a minimal repo that I could use to investigate this?

Does this still happen with v33 of ag-grid-react?

**Comment by Amritpd** [comment]
@StephenCooper I can try to set up a repo if need be. I updated to the latest libraries 

─ ag-grid-community@33.3.1
└─┬ ag-grid-react@33.3.1

And now I get the console message: Error: AG Grid: error #272 "No AG Grid modules are registered! It is recommended to start with all Community features via the AllCommunityModule:\n...
