### ISSUE TITLE
valueParser not working with agSelectCellEditor

### ISSUE THREAD

**Issue by matiacone** [ag-grid/ag-grid#8073]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```

My ValueParser does not trigger upon the `cellValueChanged` event when using `cellEditor: 'agSelectCellEditor'`

Column Def
![image](https://github.com/ag-grid/ag-grid/assets/119713839/84bad749-5deb-4952-b2cd-86e40dd4e189)

Event fires --> log statement does not trigger

valueParsers working for other columns that are NOT using a speicifed cellEditor

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by radubl** [comment]
this does not work with agRichSelectCellEditor either

**Comment by vipulchaudhary1601** [comment]
> Hi
> 
> Thank you for submitting this on Github.
> 
> As this has been open without any further interaction for a while, I will be closing this issue.
> 
> If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.
> 
> Kind regards, Zoheil

I am still facing this issue in version 28.2.1. Could you please reopen this issue or provide further guidance on how to resolve it?

**Comment by AG-Zoheil** [comment]
Hi,

The most efficient way for us to look into potential bugs would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

**However please note:** I can see you have mentioned you're using AG-Grid `v28`. Our current latest version is `v32`. If the bug is resolved in a later versions our recommendation will be to upgrade your version of AG-Grid in your application so that you can benefit from all the improvements in functionality, stability, theming and performance we've made since the version you're using.

Kind regards,
Zoheil

**Comment by gespinha** [comment]
> Hi,
> 
> The most efficient way for us to look into potential bugs would be for you to provide a live example reproducing the issue.
> 
> Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.
> 
> **However please note:** I can see you have mentioned you're using AG-Grid `v28`. Our current latest version is `v32`. If the bug is resolved in a later versions our recommendation will be to upgrade your version of AG-Grid in your application so that you can benefit from all the improvements in functionality, stability, theming and performance we've made since the version you're using.
> 
> Kind regards, Zoheil

I'm using AG-Grid v32.2.1 and can confirm this still doesn't work. Here is a working example of this issue in action: https://codesandbox.io/p/sandbox/ag-grid-example-jzgqks

In the example you'll see that when editing the column "Make" the `valueParser` option is not working.

**Comment by AG-Zoheil** [comment]
Hi @gespinha,

We've looked into this in more detail and we don't believe this is a bug as we don’t parse the values because `agRichSelectCellEditor` is not an input field. The list of valid values is provided by the user and should already the parsed.

**Comment by 0xbk** [comment]
> Hi [@gespinha](https://github.com/gespinha),
> 
> We've looked into this in more detail and we don't believe this is a bug as we don’t parse the values because `agRichSelectCellEditor` is not an input field. The list of valid values is provided by the user and should already the parsed.

I don't believe the values in the `agRichSelectCellEditor` should be assumed to already be parsed. For instance, say I wanted to display in the editor values such as "2025 Q1", "2025 Q2", "2025 Q3", etc. but would like to convert those values to a `Date` to be saved (such as `new Date(2025, 2, 31)`, `new Date(2025, 5, 30)`, and `new Date(2025, 8, 30)`, respectively). Is there a way to handle this in AG Grid?
